import { OnboardingStep } from '../types/onboarding';

export const ONBOARDING_STEPS: OnboardingStep[] = [
  {
    id: 'welcome',
    title: 'Welcome to Auto-Trading!',
    description: 'Let\'s take a quick tour to help you get started with our powerful trading platform.',
    targetComponent: 'welcome',
    position: 'center',
    action: 'none',
    highlight: false,
    skipable: false,
    order: 0,
  },
  {
    id: 'marketplace',
    title: 'Marketplace',
    description: 'Discover and explore trading strategies, formulas, and tools created by our community.',
    targetComponent: 'marketplace',
    position: 'bottom',
    arrowDirection: 'up',
    action: 'tap',
    highlight: true,
    skipable: true,
    order: 1,
  },
  {
    id: 'formula-builder',
    title: 'Formula Builder',
    description: 'Create custom trading formulas and strategies using our intuitive drag-and-drop interface.',
    targetComponent: 'formula-builder',
    position: 'right',
    arrowDirection: 'left',
    action: 'tap',
    highlight: true,
    skipable: true,
    order: 2,
  },
  {
    id: 'risk-widget',
    title: 'Risk Management',
    description: 'Monitor and control your trading risks with real-time analytics and alerts.',
    targetComponent: 'risk-widget',
    position: 'top',
    arrowDirection: 'down',
    action: 'tap',
    highlight: true,
    skipable: true,
    order: 3,
  },
  {
    id: 'notifications',
    title: 'Notifications',
    description: 'Stay updated with trading alerts, market changes, and important updates.',
    targetComponent: 'notifications',
    position: 'left',
    arrowDirection: 'right',
    action: 'tap',
    highlight: true,
    skipable: true,
    order: 4,
  },
  {
    id: 'paper-trade',
    title: 'Paper Trading',
    description: 'Practice your strategies risk-free with our paper trading simulator.',
    targetComponent: 'paper-trade',
    position: 'bottom',
    arrowDirection: 'up',
    action: 'tap',
    highlight: true,
    skipable: true,
    order: 5,
  },
  {
    id: 'first-subscription',
    title: 'First Subscription',
    description: 'Subscribe to premium features and advanced trading tools.',
    targetComponent: 'subscription',
    position: 'center',
    action: 'tap',
    highlight: true,
    skipable: true,
    order: 6,
  },
  {
    id: 'approval',
    title: 'Account Approval',
    description: 'Complete your account verification to start live trading.',
    targetComponent: 'approval',
    position: 'center',
    action: 'tap',
    highlight: true,
    skipable: true,
    order: 7,
  },
  {
    id: 'live-trade',
    title: 'Live Trading',
    description: 'Execute real trades with your approved strategies and risk management.',
    targetComponent: 'live-trade',
    position: 'center',
    action: 'tap',
    highlight: true,
    skipable: true,
    order: 8,
  },
  {
    id: 'basket',
    title: 'Trading Basket',
    description: 'Organize and manage multiple trading positions in one place.',
    targetComponent: 'basket',
    position: 'top',
    arrowDirection: 'down',
    action: 'tap',
    highlight: true,
    skipable: true,
    order: 9,
  },
];

export const WELCOME_TOUR_STEPS = [
  {
    id: 'intro',
    title: 'Welcome to Auto-Trading',
    description: 'Your intelligent trading companion',
    image: 'welcome',
  },
  {
    id: 'features',
    title: 'Powerful Features',
    description: 'Advanced trading tools at your fingertips',
    image: 'features',
  },
  {
    id: 'safety',
    title: 'Safe & Secure',
    description: 'Bank-level security for your investments',
    image: 'security',
  },
  {
    id: 'community',
    title: 'Join the Community',
    description: 'Connect with traders worldwide',
    image: 'community',
  },
];

export const COACH_TRIGGERS = [
  { screenName: 'MarketplaceScreen', componentId: 'marketplace-tab', stepId: 'marketplace' },
  { screenName: 'FormulaBuilderScreen', componentId: 'formula-builder-tab', stepId: 'formula-builder' },
  { screenName: 'RiskScreen', componentId: 'risk-widget', stepId: 'risk-widget' },
  { screenName: 'NotificationScreen', componentId: 'notification-bell', stepId: 'notifications' },
  { screenName: 'TradingScreen', componentId: 'paper-trade-button', stepId: 'paper-trade' },
  { screenName: 'SubscriptionScreen', componentId: 'subscription-card', stepId: 'first-subscription' },
  { screenName: 'ProfileScreen', componentId: 'approval-status', stepId: 'approval' },
  { screenName: 'TradingScreen', componentId: 'live-trade-button', stepId: 'live-trade' },
  { screenName: 'PortfolioScreen', componentId: 'basket-widget', stepId: 'basket' },
];